{% set name = "movis" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rezoo/movis/archive/v{{ version }}.tar.gz
  sha256: 7df4ed7f38e24580bb738d87cddba40e0370bd82101a7fd480e12d980f2ae085

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.18.1
    - librosa >=0.10.1
    - pillow >=8.2.0
    - imageio >=2.31.1
    - imageio-ffmpeg >=0.4.8
    - tqdm >=4.46.0
    - diskcache >=5.6.1
    - opencv >=4.8.0
    - pyside6 >=6.5.2

test:
  imports:
    - movis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rezoo.github.io/movis/
  dev_url: https://github.com/rezoo/movis
  summary: A video editing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
